---
apiVersion: v1
kind: Service
metadata:
  name: apiv2
  labels:
    app: apiv2
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: apiv2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiv2
  labels:
    app: apiv2
spec:
  selector:
    matchLabels:
      app: apiv2
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apiv2
    spec:
      initContainers:
        - name: flyway-migrations
          image: quay.io/rblake/microservice-db:v2
          args:
            - migrate
          envFrom:
            - secretRef:
                name: apiv2-conf
                optional: false
          volumeMounts:
            - name: flyway-conf
              mountPath: /flyway/conf/envs/prod/
      containers:
        - name: microservice
          image: quay.io/rblake/microservice:v2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 512Mi
              cpu: 0.5
          readinessProbe:
            httpGet:
              path: /people
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          envFrom:
            - secretRef:
                name: apiv2-conf
                optional: false
          ports:
            - containerPort: 8080
              name: http
      volumes:
        - name: flyway-conf
          secret:
            secretName: apiv2-flyway-conf