name: db-migration-review
on:
  pull_request:
    types: [labeled]
jobs:
  request-db-migration-review:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/db-migrations-reviewers.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

